-- ESQUEMA COMPLETO - SISTEMA DE GESTIÓN DE RESTAURANTE
-- Este script es idempotente: puedes ejecutarlo varias veces sin errores.

-- 0. LIMPIEZA PREVIA (Opcional, descomentar si se desea resetear todo)
-- DROP TABLE IF EXISTS public.auditoria_financiera;
-- DROP TABLE IF EXISTS public.pedidos;
-- DROP TABLE IF EXISTS public.menu;
-- DROP TABLE IF EXISTS public.solicitudes_servicio;

-- 1. CREACIÓN DE TABLAS
-- Aseguramos que las tablas existan antes de configurar políticas o realtime.

CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    mesa VARCHAR(50) NOT NULL,
    mesero VARCHAR(100) NOT NULL,
    items JSONB NOT NULL,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(50) NOT NULL DEFAULT 'pendiente',
    -- Columnas para Flujo de Pago Móvil
    metodo_pago VARCHAR(50) DEFAULT 'efectivo',
    pago_referencia VARCHAR(100),
    pago_telefono VARCHAR(50),
    pago_banco VARCHAR(100),
    estado_pago VARCHAR(50) DEFAULT 'pendiente',
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- TABLA DE AJUSTES GLOBALES
CREATE TABLE IF NOT EXISTS ajustes (
    clave TEXT PRIMARY KEY,
    valor JSONB,
    actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insertar valores iniciales si no existen
INSERT INTO ajustes (clave, valor) VALUES 
('pago_movil', '{"banco": "BANESCO (0134)", "rif": "J-50123456-7", "telefono": "04121234567"}'),
('passwords', '{"caja": "admin", "inventario": "admin", "config": "admin"}')
ON CONFLICT (clave) DO NOTHING;

-- FUNCIÓN PARA LIMPIAR AUDITORÍA Y REINICIAR IDs
CREATE OR REPLACE FUNCTION limpiar_auditoria_completa()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE auditoria_financiera RESTART IDENTITY;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TABLE IF NOT EXISTS public.auditoria_financiera (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    metodo_pago VARCHAR(50) NOT NULL,
    mesero VARCHAR(100) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) UNIQUE NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    descripcion TEXT DEFAULT '',
    emoji VARCHAR(10) DEFAULT '🍔',
    disponible BOOLEAN DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.solicitudes_servicio (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    mesa VARCHAR(50) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'pendiente',
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. CONFIGURAR TIEMPO REAL (REALTIME)
-- Aseguramos que la publicación exista y asociamos las tablas.
-- NOTA: Si esto falla, intenta ejecutarlo fuera de una transacción.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        CREATE PUBLICATION supabase_realtime;
    END IF;
END $$;

-- Intentar añadir tablas a la publicación de manera segura.
-- Si ya estaban, 'SET TABLE' simplemente refresca la lista.
ALTER PUBLICATION supabase_realtime SET TABLE 
    public.pedidos, 
    public.auditoria_financiera, 
    public.menu, 
    public.solicitudes_servicio;

-- 3. TRIGGER DE ACTUALIZACIÓN AUTOMÁTICA DE TIMESTAMP
CREATE OR REPLACE FUNCTION public.actualizar_timestamp_actualizado_en()
RETURNS TRIGGER AS $$
BEGIN
    NEW.actualizado_en = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_actualizar_pedidos_actualizado_en ON public.pedidos;
CREATE TRIGGER trigger_actualizar_pedidos_actualizado_en
    BEFORE UPDATE ON public.pedidos
    FOR EACH ROW
    EXECUTE FUNCTION public.actualizar_timestamp_actualizado_en();

-- 4. SEGURIDAD A NIVEL DE FILAS (RLS)
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria_financiera ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitudes_servicio ENABLE ROW LEVEL SECURITY;

-- 5. LIMPIEZA Y CREACIÓN DE POLÍTICAS
-- Usamos DROP POLICY IF EXISTS para evitar errores de duplicados.

-- Políticas para 'pedidos'
DROP POLICY IF EXISTS "Permitir lectura pública de pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir inserción pública de pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir actualización pública de pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Permitir borrado público de pedidos" ON public.pedidos;

CREATE POLICY "Permitir lectura pública de pedidos" ON public.pedidos FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Permitir inserción pública de pedidos" ON public.pedidos FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Permitir actualización pública de pedidos" ON public.pedidos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permitir borrado público de pedidos" ON public.pedidos FOR DELETE TO anon, authenticated USING (true);

-- Políticas para 'auditoria_financiera'
DROP POLICY IF EXISTS "Permitir lectura pública de auditoria" ON public.auditoria_financiera;
DROP POLICY IF EXISTS "Permitir inserción pública de auditoria" ON public.auditoria_financiera;

CREATE POLICY "Permitir lectura pública de auditoria" ON public.auditoria_financiera FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Permitir inserción pública de auditoria" ON public.auditoria_financiera FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Políticas para 'menu'
DROP POLICY IF EXISTS "Permitir lectura pública de menú" ON public.menu;
DROP POLICY IF EXISTS "Permitir inserción pública de menú" ON public.menu;
DROP POLICY IF EXISTS "Permitir actualización pública de menú" ON public.menu;
DROP POLICY IF EXISTS "Permitir borrado público de menú" ON public.menu;

CREATE POLICY "Permitir lectura pública de menú" ON public.menu FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Permitir inserción pública de menú" ON public.menu FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Permitir actualización pública de menú" ON public.menu FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permitir borrado público de menú" ON public.menu FOR DELETE TO anon, authenticated USING (true);

-- Políticas para 'solicitudes_servicio'
DROP POLICY IF EXISTS "Permitir lectura pública de solicitudes_servicio" ON public.solicitudes_servicio;
DROP POLICY IF EXISTS "Permitir inserción pública de solicitudes_servicio" ON public.solicitudes_servicio;
DROP POLICY IF EXISTS "Permitir actualización pública de solicitudes_servicio" ON public.solicitudes_servicio;
DROP POLICY IF EXISTS "Permitir borrado público de solicitudes_servicio" ON public.solicitudes_servicio;

CREATE POLICY "Permitir lectura pública de solicitudes_servicio" ON public.solicitudes_servicio FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Permitir inserción pública de solicitudes_servicio" ON public.solicitudes_servicio FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Permitir actualización pública de solicitudes_servicio" ON public.solicitudes_servicio FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permitir borrado público de solicitudes_servicio" ON public.solicitudes_servicio FOR DELETE TO anon, authenticated USING (true);

-- 6. DATOS INICIALES (SEMILLA) PARA EL MENÚ
INSERT INTO public.menu (nombre, precio, categoria, descripcion, emoji, disponible)
VALUES
  ('Hamburguesa Premium', 12.50, 'COMIDA', 'Jugosa carne de res con queso derretido, lechuga, tomate y carnes seleccionadas.', '🍔', TRUE),
  ('Pizza Personal Pepperoni', 15.00, 'COMIDA', 'Deliciosa masa artesanal dorada con abundante salsa de tomate, mozzarella y rodajas de pepperoni.', '🍕', TRUE),
  ('Tacos de Res (x3)', 8.50, 'COMIDA', 'Tres tacos crujientes servidos con carne picada de primera, salsa de tomate picante y cilantro fresco.', '🌮', TRUE),
  ('Parrilla Familiar (al Peso)', 24.00, 'COMIDA', 'Exquisito surtido de carnes premium cocidas a la brasa, servido por kilo o gramo.', '🥩', TRUE),
  ('Chicharrón Crujiente (al Peso)', 18.00, 'COMIDA', 'Tradicional chicharrón de cerdo bien crujiente con arepitas, servido por kilo o gramo.', '🥓', TRUE),
  ('Costillas de Cerdo (al Peso)', 21.00, 'COMIDA', 'Costillas de cerdo ahumadas con glaseado especial BBQ de la casa, servidas por kilo o gramo.', '🍖', TRUE),
  ('Papas Fritas', 4.00, 'ACOMPANAMIENTO', 'Crujientes y doradas, ligeramente sazonadas con sal marina.', '🍟', TRUE),
  ('Alitas BBQ', 9.50, 'ACOMPANAMIENTO', 'Alitas de pollo glaseadas con una adictiva salsa barbacoa dulce y ahumada.', '🍗', TRUE),
  ('Té Frío Limón', 3.00, 'BEBIDA', 'Té natural helado con jugo de limón fresco y endulzado.', '🍹', TRUE),
  ('Refresco Sabor Cola', 2.55, 'BEBIDA', 'Vaso de refresco burbujeante frío con cubitos de hielo.', '🥤', TRUE),
  ('Agua Mineral', 2.00, 'BEBIDA', 'Agua de manantial carbonatada refrescante y cristalina.', '💧', TRUE)
ON CONFLICT (nombre) DO UPDATE 
SET precio = EXCLUDED.precio, 
    categoria = EXCLUDED.categoria,
    descripcion = EXCLUDED.descripcion,
    emoji = EXCLUDED.emoji;

-- 7. SISTEMA DE LIMPIEZA AUTOMÁTICA (CADA 24 HORAS)
-- Esta función borra pedidos, auditoría y solicitudes, reiniciando los contadores (IDs).
CREATE OR REPLACE FUNCTION public.limpiar_datos_diarios()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE public.pedidos RESTART IDENTITY CASCADE;
    TRUNCATE TABLE public.auditoria_financiera RESTART IDENTITY CASCADE;
    TRUNCATE TABLE public.solicitudes_servicio RESTART IDENTITY CASCADE;
END;
$$ LANGUAGE plpgsql;

/* 
  INSTRUCCIONES PARA ACTIVAR LA LIMPIEZA AUTOMÁTICA EN SUPABASE:
  
  1. Ve a tu Dashboard de Supabase > Database > Extensions.
  2. Busca y activa la extensión "pg_cron".
  3. Ve al SQL Editor y ejecuta:
     
     SELECT cron.schedule('limpieza-diaria-restaurante', '0 0 * * *', 'SELECT public.limpiar_datos_diarios()');
     
  Esto hará que todos los días a medianoche se limpie la app automáticamente.
*/

-- 8. SISTEMA DE VENTAS (POS) - PRODUCTOS POR PESO Y UNIDAD
CREATE TABLE IF NOT EXISTS public.productos_venta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras text UNIQUE NOT NULL,
    nombre text NOT NULL,
    categoria text NOT NULL CHECK (categoria IN ('licores', 'alimentos', 'carnes')),
    unidad_medida text NOT NULL CHECK (unidad_medida IN ('unid', 'kg')),
    precio_base numeric(10,2) NOT NULL,
    stock numeric(10,3) NOT NULL DEFAULT 0,
    stock_minimo numeric(10,3) NOT NULL DEFAULT 5,
    created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_productos_barras ON public.productos_venta (codigo_barras);

-- 9. HISTORIAL DE VENTAS POS
CREATE TABLE IF NOT EXISTS public.ventas_pos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total numeric(10,2) NOT NULL,
    articulos jsonb NOT NULL, -- Lista de items vendidos
    fecha timestamptz DEFAULT now()
);

-- Insertar algunos productos iniciales si no existen
INSERT INTO public.productos_venta (codigo_barras, nombre, categoria, unidad_medida, precio_base, stock, stock_minimo)
VALUES 
('7501000', 'Ron Añejo 750ml', 'licores', 'unid', 250.00, 20, 5),
('7502000', 'Vino Tinto Reserva', 'licores', 'unid', 450.00, 15, 3),
('1001', 'Corte Rib Eye Prime', 'carnes', 'kg', 580.00, 12.500, 2.000),
('1002', 'Filete de Res', 'carnes', 'kg', 420.00, 8.200, 2.000),
('1003', 'Parrilla Real (Familiar)', 'carnes', 'kg', 590.00, 15.000, 2.000),
('1004', 'Chicharrón Crujiente', 'carnes', 'kg', 390.00, 20.000, 3.000),
('1005', 'Costillas de Cerdo Ahumadas', 'carnes', 'kg', 480.00, 25.000, 4.000),
('2001', 'Pan Artesanal', 'alimentos', 'unid', 45.00, 30, 10)
ON CONFLICT (codigo_barras) DO NOTHING;
